name: Test Go

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.21.x"
            - name: Install ZeroMQ
              run: sudo apt-get update && sudo apt-get install -y libzmq3-dev
            - name: Install dependencies
              run: go get ./...
            - name: Build
              run: go build ./...
            - name: Test
              run: go test ./... -v
